### ISSUE TITLE
Wandering Trader & Trader LLama on spawn event listener

### ISSUE THREAD

**Issue by Slachy-Dot** [ThijmenGThN/TraderNotify#16]
I did look a bid at your code and atm you loop true all mobs in a world would it not be a better idea to use the entity spawn event and look at what player a trader near by has spawned ?

**Comment by ThijmenGThN** [comment]
Thank you for reaching out to me, 

I have tried that in a previous version, and it did not detect the wandering trader unfortunately.

Since you opened this issue I will add this to my to-do list to make this work.

Let me know what you think, I appreciate your feedback.


~ Thijmen

**Comment by ThijmenGThN** [comment]
I will be marking this as fixed since its better to have it like its now, it's supposed to show the message even though the server reloaded, and a wandering trader is present.

This can be reopened if you have a better method with a fork / pull request.

Thank you for bringing this to my attention, I really appreciate it.
